package cn.ymsys.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBuUCompetitiveTender<M extends BaseBuUCompetitiveTender<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setBuTenderId(java.lang.Integer buTenderId) {
		set("bu_tender_id", buTenderId);
		return (M)this;
	}
	
	public java.lang.Integer getBuTenderId() {
		return getInt("bu_tender_id");
	}

	public M setSysUserId(java.lang.Integer sysUserId) {
		set("sys_user_id", sysUserId);
		return (M)this;
	}
	
	public java.lang.Integer getSysUserId() {
		return getInt("sys_user_id");
	}

	public M setContext(java.lang.String context) {
		set("context", context);
		return (M)this;
	}
	
	public java.lang.String getContext() {
		return getStr("context");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
