package com.jyd.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("basics", "id", Basics.class);
		arp.addMapping("bu_comment", "id", BuComment.class);
		arp.addMapping("bu_photo", "id", BuPhoto.class);
		arp.addMapping("bu_u_authentication", "id", BuUAuthentication.class);
		arp.addMapping("bu_u_company", "id", BuUCompany.class);
		arp.addMapping("bu_u_competitive_tender", "id", BuUCompetitiveTender.class);
		arp.addMapping("bu_u_product", "id", BuUProduct.class);
		arp.addMapping("bu_u_tender", "id", BuUTender.class);
		arp.addMapping("sys_ad", "id", SysAd.class);
		arp.addMapping("sys_user", "id", SysUser.class);
	}
}

