package com.jyd.common.model;

import com.jyd.common.model.base.BaseBuUAuthentication;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuUAuthentication extends BaseBuUAuthentication<BuUAuthentication> {
	
}
