package com.jyd.common.model;

import com.jyd.common.model.base.BaseBuUCompetitiveTender;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuUCompetitiveTender extends BaseBuUCompetitiveTender<BuUCompetitiveTender> {
	
}
