package com.jyd.common.model;

import com.jyd.common.model.base.BaseBuUProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuUProduct extends BaseBuUProduct<BuUProduct> {
	
}
