package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBuUserProduct<M extends BaseBuUserProduct<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setBuCompanyId(java.lang.Integer buCompanyId) {
		set("bu_company_id", buCompanyId);
		return (M)this;
	}
	
	public java.lang.Integer getBuCompanyId() {
		return getInt("bu_company_id");
	}

	public M setBaProductTypeId(java.lang.Integer baProductTypeId) {
		set("ba_product_type_id", baProductTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getBaProductTypeId() {
		return getInt("ba_product_type_id");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setSpecifications(java.lang.String specifications) {
		set("specifications", specifications);
		return (M)this;
	}
	
	public java.lang.String getSpecifications() {
		return getStr("specifications");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setContext(java.lang.String context) {
		set("context", context);
		return (M)this;
	}
	
	public java.lang.String getContext() {
		return getStr("context");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

}
