package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBasics<M extends BaseBasics<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setKeyy(java.lang.String keyy) {
		set("keyy", keyy);
		return (M)this;
	}
	
	public java.lang.String getKeyy() {
		return getStr("keyy");
	}

	public M setValuee(java.lang.Integer valuee) {
		set("valuee", valuee);
		return (M)this;
	}
	
	public java.lang.Integer getValuee() {
		return getInt("valuee");
	}

	public M setCloumnName(java.lang.String cloumnName) {
		set("cloumn_name", cloumnName);
		return (M)this;
	}
	
	public java.lang.String getCloumnName() {
		return getStr("cloumn_name");
	}

	public M setTableName(java.lang.String tableName) {
		set("table_name", tableName);
		return (M)this;
	}
	
	public java.lang.String getTableName() {
		return getStr("table_name");
	}

}
