package cn.ymsys.api.common.model;

import cn.ymsys.api.common.model.base.BaseBasics;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Basics extends BaseBasics<Basics> {
	
}
