package cn.ymsys.api.common.model;

import cn.ymsys.api.common.model.base.BaseBuComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuComment extends BaseBuComment<BuComment> {
	
}
