package cn.ymsys.api.common.model;

import cn.ymsys.api.common.model.base.BaseBuUAuthentication;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuUAuthentication extends BaseBuUAuthentication<BuUAuthentication> {
	
}
