package cn.ymsys.api.common.model;

import cn.ymsys.api.common.model.base.BaseBuUCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuUCompany extends BaseBuUCompany<BuUCompany> {
}
