package cn.ymsys.api.common.model;

import cn.ymsys.api.common.model.base.BaseBuUCompetitiveTender;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuUCompetitiveTender extends BaseBuUCompetitiveTender<BuUCompetitiveTender> {
	
}
