package cn.ymsys.api.common.model;

import cn.ymsys.api.common.model.base.BaseBuUProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuUProduct extends BaseBuUProduct<BuUProduct> {
	
}
