package cn.ymsys.api.common.model;

import cn.ymsys.api.common.model.base.BaseSysExecutionJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysExecutionJob extends BaseSysExecutionJob<SysExecutionJob> {
	
}
