package cn.ymsys.api.common.model;

import cn.ymsys.api.common.model.base.BaseSysExecutionQueue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysExecutionQueue extends BaseSysExecutionQueue<SysExecutionQueue> {
	
}
