package cn.ymsys.api.common.model;

import cn.ymsys.api.common.model.base.BaseSysUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> {
	
}
