package cn.ymsys.api.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysExecutionJob<M extends BaseSysExecutionJob<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setJobName(java.lang.String jobName) {
		set("job_name", jobName);
		return (M)this;
	}
	
	public java.lang.String getJobName() {
		return getStr("job_name");
	}

	public M setJobType(java.lang.Integer jobType) {
		set("job_type", jobType);
		return (M)this;
	}
	
	public java.lang.Integer getJobType() {
		return getInt("job_type");
	}

	public M setJobState(java.lang.Integer jobState) {
		set("job_state", jobState);
		return (M)this;
	}
	
	public java.lang.Integer getJobState() {
		return getInt("job_state");
	}

	public M setJobContent(java.lang.String jobContent) {
		set("job_content", jobContent);
		return (M)this;
	}
	
	public java.lang.String getJobContent() {
		return getStr("job_content");
	}

}
