package cn.ymsys.api.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysExecutionQueue<M extends BaseSysExecutionQueue<M>> extends Model<M> implements IBean {

	public M setJobId(java.lang.Integer jobId) {
		set("job_id", jobId);
		return (M)this;
	}
	
	public java.lang.Integer getJobId() {
		return getInt("job_id");
	}

	public M setJobState(java.lang.Integer jobState) {
		set("job_state", jobState);
		return (M)this;
	}
	
	public java.lang.Integer getJobState() {
		return getInt("job_state");
	}

	public M setJobSingla(java.lang.Integer jobSingla) {
		set("job_singla", jobSingla);
		return (M)this;
	}
	
	public java.lang.Integer getJobSingla() {
		return getInt("job_singla");
	}

	public M setJobTime(java.util.Date jobTime) {
		set("job_time", jobTime);
		return (M)this;
	}
	
	public java.util.Date getJobTime() {
		return get("job_time");
	}

	public M setJobDesc(java.lang.String jobDesc) {
		set("job_desc", jobDesc);
		return (M)this;
	}
	
	public java.lang.String getJobDesc() {
		return getStr("job_desc");
	}

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

}
