package cn.ymsys.api.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBuPhoto<M extends BaseBuPhoto<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setBuPhotoTypeId(java.lang.Integer buPhotoTypeId) {
		set("bu_photo_type_id", buPhotoTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getBuPhotoTypeId() {
		return getInt("bu_photo_type_id");
	}

	public M setBuObjectId(java.lang.Integer buObjectId) {
		set("bu_object_id", buObjectId);
		return (M)this;
	}
	
	public java.lang.Integer getBuObjectId() {
		return getInt("bu_object_id");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

}
