package cn.ymsys.api.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBuTenderPhoto<M extends BaseBuTenderPhoto<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setTenderId(java.lang.Integer tenderId) {
		set("tender_id", tenderId);
		return (M)this;
	}
	
	public java.lang.Integer getTenderId() {
		return getInt("tender_id");
	}

}
