package cn.ymsys.api.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBuUAuthentication<M extends BaseBuUAuthentication<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSysUserId(java.lang.Integer sysUserId) {
		set("sys_user_id", sysUserId);
		return (M)this;
	}
	
	public java.lang.Integer getSysUserId() {
		return getInt("sys_user_id");
	}

	public M setBaPaymentTypeId(java.lang.Integer baPaymentTypeId) {
		set("ba_payment_type_id", baPaymentTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getBaPaymentTypeId() {
		return getInt("ba_payment_type_id");
	}

	public M setApproval(java.lang.Integer approval) {
		set("approval", approval);
		return (M)this;
	}
	
	public java.lang.Integer getApproval() {
		return getInt("approval");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
