package cn.ymsys.api.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBuUAuthentication<M extends BaseBuUAuthentication<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSysUserId(java.lang.Integer sysUserId) {
		set("sys_user_id", sysUserId);
		return (M)this;
	}
	
	public java.lang.Integer getSysUserId() {
		return getInt("sys_user_id");
	}

	public M setBaPaymentTypeId(java.lang.Integer baPaymentTypeId) {
		set("ba_payment_type_id", baPaymentTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getBaPaymentTypeId() {
		return getInt("ba_payment_type_id");
	}

	public M setApproval(java.lang.Integer approval) {
		set("approval", approval);
		return (M)this;
	}
	
	public java.lang.Integer getApproval() {
		return getInt("approval");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
		return (M)this;
	}
	
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	public M setCompanyOrg(java.lang.String companyOrg) {
		set("company_org", companyOrg);
		return (M)this;
	}
	
	public java.lang.String getCompanyOrg() {
		return getStr("company_org");
	}

	public M setRealName(java.lang.String realName) {
		set("real_name", realName);
		return (M)this;
	}
	
	public java.lang.String getRealName() {
		return getStr("real_name");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setOrgNumber(java.lang.String orgNumber) {
		set("org_number", orgNumber);
		return (M)this;
	}
	
	public java.lang.String getOrgNumber() {
		return getStr("org_number");
	}

	public M setAuthTime(java.util.Date authTime) {
		set("auth_time", authTime);
		return (M)this;
	}
	
	public java.util.Date getAuthTime() {
		return get("auth_time");
	}

}
