package cn.ymsys.common.model;

import cn.ymsys.common.model.base.BaseBuUTender;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuUTender extends BaseBuUTender<BuUTender> {
	
}
